Repository turicas/covid19-br, pull requests merged in 2020-04, with the labels that each got.

#20 implementa a validação contínua de dados com o Goodtables
  README.md
  datapackage.json
  requirements.txt
  validate.sh
Labels: enhancement

#72 implementa pytest no Docker com GitHub Actions
  .github/workflows/pytest.yaml
  Dockerfile
  Makefile
  README.md
  requirements-development.txt
  tests/sample_test.py
Labels: automation, enhancement

#83 adiciona os novos CVSs para validação no Data Package
  datapackage.json
Labels: automation

#111 Atualiza url's da API
  api.md
Labels: documentation
